### ISSUE TITLE
Сделать компонент footer

### ISSUE THREAD

**Issue by BKonstantine** [FSD-For-Self-Dev/LinguistaFrontend#119]
https://www.figma.com/design/uN5ar9LRpEngLp1BgICkg6/Linguista-Voc-%7C-Makets?node-id=7781-135179&t=8nML61qgoiVjNEt8-4

Сделать заготовку для компонента footer. В данный момент, интересует структура компонента.

**Comment by qwavy** [comment]
Извиняюсь , вчера только заметил . 
вот я сделал . как мне его вам загрузить? ветку создать и туда закинуть?

**Comment by qwavy** [comment]
И еще как загружаем шрифты и картинки?

**Comment by BKonstantine** [comment]
Лучше пиши в телегу ) Тут я не всегда успею увидеть) Но в целом ты все сделал верно)
