### ISSUE TITLE
Task: Верстка блока Определения профиля слова + добавить страницу Все опредления

### ISSUE THREAD

**Issue by BU-Marina** [FSD-For-Self-Dev/LinguistaFrontend#13]
![image](https://github.com/FSD-For-Self-Dev/LinguistaFrontend/assets/77714654/9f8945a9-da1c-446e-9e66-090d61225d7a)

## Epic Parent

[Feature: CWord Profile Page | Страница профиля слова](https://github.com/FSD-For-Self-Dev/LinguistaAPI/issues/27)

**Comment by Anastacia-Tesli** [comment]
Не забыть сделать вариант пустой страницы Все определения

**Comment by azozulya** [comment]
Обновление дизайна 

![Image](https://github.com/FSD-For-Self-Dev/LinguistaFrontend/assets/1482886/d93f28c7-528b-40b2-bade-57205adfddbb)
